import { NextRequest, NextResponse } from 'next/server';
import { getSystemPrompt } from '@/lib/ai/prompts';
import { AIInsightFeature } from '@/lib/types';

type ChatMessage = {
  role: 'user' | 'assistant';
  content: string;
};

function getModel() {
  return process.env.GROQ_MODEL || 'llama-3.1-8b-instant';
}

function getApiKey() {
  return process.env.GROQ_API_KEY || process.env.QWEN_API_KEY || '';
}

function getBaseUrl() {
  return process.env.GROQ_BASE_URL || 'https://api.groq.com/openai/v1';
}

function delay(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function requestCompletion({
  apiKey,
  body,
}: {
  apiKey: string;
  body: Record<string, unknown>;
}) {
  return fetch(`${getBaseUrl()}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify(body),
  });
}

export async function POST(request: NextRequest) {
  try {
    const apiKey = getApiKey();
    if (!apiKey) {
      return NextResponse.json(
        { error: 'Missing AI provider key. Add GROQ_API_KEY to your local environment.' },
        { status: 500 }
      );
    }

    const body = await request.json();
    const feature = body.feature as AIInsightFeature | 'chat';
    const summary = body.summary;
    const question = body.question as string | undefined;
    const messages = (body.messages || []) as ChatMessage[];

    if (!feature || !summary) {
      return NextResponse.json({ error: 'Feature and summary are required.' }, { status: 400 });
    }

    const userPrompt =
      feature === 'chat'
        ? `Health summary JSON:\n${JSON.stringify(summary, null, 2)}\n\nUser question: ${question || ''}\n\nFormat the answer for easy reading with very short paragraphs or bullets when useful.`
        : `Generate insights from this health summary JSON:\n${JSON.stringify(summary, null, 2)}`;

    const payloadMessages =
      feature === 'chat'
        ? [
            { role: 'system', content: getSystemPrompt('chat') },
            ...messages.slice(-8),
            { role: 'user', content: userPrompt },
          ]
        : [
            { role: 'system', content: getSystemPrompt(feature) },
            { role: 'user', content: userPrompt },
          ];

    const requestBody = {
      model: getModel(),
      temperature: 0.25,
      max_tokens: feature === 'chat' ? 120 : 220,
      response_format: feature === 'chat' ? undefined : { type: 'json_object' },
      messages: payloadMessages,
    };

    let response = await requestCompletion({
      apiKey,
      body: requestBody,
    });

    if (response.status === 429) {
      await delay(7000);
      response = await requestCompletion({
        apiKey,
        body: requestBody,
      });
    }

    if (!response.ok) {
      const errorText = await response.text();
      if (
        feature !== 'chat' &&
        (errorText.includes('json_validate_failed') || errorText.includes('Failed to generate JSON'))
      ) {
        const retryResponse = await requestCompletion({
          apiKey,
          body: {
            model: getModel(),
            temperature: 0.2,
            max_tokens: 220,
            messages: [
              { role: 'system', content: `${getSystemPrompt(feature)} Keep the JSON extremely short and compact.` },
              {
                role: 'user',
                content: `Return compact valid JSON only for this summary:\n${JSON.stringify(summary)}`,
              },
            ],
          },
        });

        if (retryResponse.ok) {
          const retryData = await retryResponse.json();
          const retryContent = retryData?.choices?.[0]?.message?.content;
          if (retryContent) {
            try {
              return NextResponse.json(JSON.parse(retryContent));
            } catch {
              return NextResponse.json({
                title: 'AI Insights',
                insights: [retryContent],
                summary: 'Generated by AI.',
              });
            }
          }
        }
      }

      return NextResponse.json(
        { error: `AI provider request failed: ${errorText}` },
        { status: response.status }
      );
    }

    const data = await response.json();
    const content = data?.choices?.[0]?.message?.content;

    if (!content) {
      return NextResponse.json({ error: 'No content returned by AI provider.' }, { status: 502 });
    }

    if (feature === 'chat') {
      return NextResponse.json({ answer: content });
    }

    let parsed;
    try {
      parsed = JSON.parse(content);
    } catch {
      parsed = {
        title: 'AI Insights',
        insights: [content],
        summary: 'Generated by AI.',
      };
    }

    return NextResponse.json(parsed);
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unexpected AI error.';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
